-- Migration 0039: graph_theories
-- Durable theories generated by the self-evolution loop. A theory is a
-- deterministic, symbolic generalization derived from observed graph
-- structure (cross-galaxy correlations, redundancy clusters, hierarchy
-- composition, cognitive-type distribution) gated by evolution pressure λ.
-- Theories are bounded per cycle and survive restarts.

CREATE TABLE IF NOT EXISTS graph_theories (
    id                 BIGSERIAL PRIMARY KEY,
    theory_id          VARCHAR(64)  NOT NULL,
    tenant_id          VARCHAR(64)  NOT NULL,
    graph_id           VARCHAR(64)  NOT NULL,
    theory_type        VARCHAR(32)  NOT NULL,
    description        TEXT NOT NULL DEFAULT '',
    confidence         DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    evidence_node_ids  JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata_json      JSONB NOT NULL DEFAULT '{}'::jsonb,
    graph_version      INTEGER NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_graph_theories_theory
    ON graph_theories (theory_id, tenant_id, graph_id);
CREATE INDEX IF NOT EXISTS idx_graph_theories_tenant_graph
    ON graph_theories (tenant_id, graph_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_graph_theories_type
    ON graph_theories (theory_type);

COMMENT ON TABLE graph_theories IS
    'Durable symbolic theories generated by the self-evolution loop.';